// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggxuuefidyewgykfhbko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdneHV1ZWZpZHlld2d5a2ZoYmtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NzIxODgsImV4cCI6MjA2NDA0ODE4OH0.Z-LIzScYxfswRzSe4AEnrw2IOmGhxBB1mZbU0hW1Skg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);